# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Colin Paterson
email: colin.paterson@york.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  Website of Colin Paterson, AAIP researcher at the University of York.
baseurl: "/~cap508/" # the subpath of your site, e.g. /blog
url: "https://www-users.york.ac.uk/~cap508/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
